call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'cocopon/iceberg.vim'
Plug 'yggdroot/indentline'
Plug 'scrooloose/nerdtree'
Plug 'leafgarland/typescript-vim'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'OmniSharp/omnisharp-vim'
Plug 'w0rp/ale'
call plug#end()

" Completition
let g:airline#extensions#ale#enabled = 1
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources = {'_': ['ale', 'foobar']}
let g:ale_completion_enabled = 1
let g:ale_list_window_size = 5
let g:ale_linters = { 'cs': ['OmniSharp'] }
nnoremap <C-G> :ALEGoToDefinition<CR>


let g:OmniSharp_server_stdio = 1
set omnifunc=ale#completion#OmniFunc
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

colorscheme iceberg

" Common
set tabstop=4 shiftwidth=4 sts=4 nowrap mouse+=a
set expandtab noswapfile
set guioptions= guifont=Ubuntu\ Mono\ 10
set clipboard=unnamedplus
set completeopt-=preview
set wildignore=*.o,*~,*.pyc,.vscode/,**/node_modules/**,.git/
set wildignore=Library,Log,Packages,Temp
set number
"
map <C-P> :FZF<CR>

"Tab
nnoremap tl :tabnext<CR>
nnoremap th :tabprevious<CR>
nnoremap te :tabnew<CR>
nnoremap tn :tabnew<CR>
nnoremap tq :tabclose<CR>

"Git
nnoremap GA :!git add .
nnoremap GC :!git commit -m "
nnoremap GP :!git push<CR>

let g:netrw_winsize=10
let g:javascript_plugin_jsdoc   = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size  = 1


autocmd FileType typescript setlocal completeopt-=menu

set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
set wildignore+=*.meta " Unity 
set wildignore+=Databases,lib,log,migrations,node_modules


let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
let g:NERDTreeIndicatorMapCustom = { 
    \ "Modified"  : "*",
    \ "Staged"    : "↗",
    \ "Untracked" : "+",
    \ "Renamed"   : "↻",
    \ "Unmerged"  : "⇆",
    \ "Deleted"   : "−",
    \ "Dirty"     : "!",
    \ "Clean"     : "·",
    \ 'Ignored'   : 'x',
    \ "Unknown"   : "?" 
    \ }
let NERDTreeIgnore = ['\.pyc$', '\.meta$', 'Temp', 'Library', 'Logs', 'Packages']
let g:ctrlp_working_path_mode = 0
