call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
" Plug 'vim-airline/vim-airline-themes'
" Plug 'vim-scripts/Align' 
" " Plug 'vim-scripts/grep.vim'
" " Plug 'noahfrederick/vim-hemisu'
Plug 'cocopon/iceberg.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'sonph/onehalf', {'rtp': 'vim/'}
Plug 'yggdroot/indentline'
" " Plug 'pangloss/vim-javascript'
Plug 'scrooloose/nerdtree'
" Plug 'mattn/emmet-vim'
" " Plug 'altercation/vim-colors-solarized'
Plug 'leafgarland/typescript-vim'
Plug 'valloric/youcompleteme'
" " Plug 'vim-latex/vim-latex'
" Plug 'reedes/vim-colors-pencil'
" " Plug 'elzr/vim-json'
Plug 'Chiel92/vim-autoformat'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tacahiroy/ctrlp-funky'
" Plug 'fatih/vim-go'
" Plug 'tpope/vim-fugitive'
call plug#end()

colorscheme onehalfdark
let g:airline_theme='onehalfdark'
let g:ctrlp_funky_syntax_highlight = 1

set tabstop=4 shiftwidth=4 sts=4 nowrap
set expandtab noswapfile
set guioptions= guifont=Ubuntu\ Mono\ 10
set clipboard=unnamedplus
set completeopt-=preview
set wildignore=*.o,*~,*.pyc,.vscode/,**/node_modules/**,.git/
set number

nnoremap tl :tabnext<CR>
nnoremap th :tabprevious<CR>
nnoremap te :tabnew<CR>
nnoremap tn :tabnew<CR>
nnoremap tq :tabclose<CR>

nnoremap GA :!git add .
nnoremap GC :!git commit -m "
nnoremap GP :!git push<CR>

map <S-a> :Align 
" map <C-P> :e **/*
nnoremap <C-k> :execute 'CtrlPFunky ' . expand('<cword>')<Cr>
nnoremap <C-g> :YcmCompleter GoTo<CR>
nnoremap <C-S-I> :YcmCompleter Format<CR>
nnoremap <C-]> :YcmCompleter FixIt<CR>

let g:netrw_winsize=10
let g:javascript_plugin_jsdoc   = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size  = 1

autocmd FileType typescript setlocal completeopt-=menu

set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
set wildignore+=Databases,lib,log,migrations,node_modules


let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
let g:NERDTreeIndicatorMapCustom = { 
    \ "Modified"  : "*",
    \ "Staged"    : "↗",
    \ "Untracked" : "+",
    \ "Renamed"   : "↻",
    \ "Unmerged"  : "⇆",
    \ "Deleted"   : "−",
    \ "Dirty"     : "!",
    \ "Clean"     : "·",
    \ 'Ignored'   : 'x',
    \ "Unknown"   : "?" 
    \ }
